# Generated by Django 3.2.1 on 2021-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocustAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updater', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('name', models.CharField(db_index=True, help_text='接口名称', max_length=100, verbose_name='接口名称')),
                ('body', models.TextField(help_text='主体信息', verbose_name='主体信息')),
                ('url', models.CharField(db_index=True, help_text='请求地址', max_length=255, verbose_name='请求地址')),
                ('method', models.CharField(help_text='请求方式', max_length=10, verbose_name='请求方式')),
                ('delete', models.IntegerField(default=0, help_text='是否删除', null=True, verbose_name='是否删除')),
                ('rig_id', models.IntegerField(db_index=True, help_text='网关API_id', null=True, verbose_name='网关API_id')),
                ('rig_env', models.IntegerField(choices=[(0, '测试环境'), (1, '生产环境'), (2, '预发布 ')], default=0, help_text='网关环境', verbose_name='网关环境')),
                ('users', models.IntegerField(default=1, help_text='并发用户数', verbose_name='并发用户数')),
                ('rate', models.IntegerField(default=1, help_text='加压速率', verbose_name='加压速率')),
                ('missiontime', models.CharField(help_text='压测时间', max_length=255, verbose_name='压测时间')),
                ('assertstr', models.CharField(help_text='断言字符串', max_length=255, verbose_name='断言字符串')),
            ],
            options={
                'verbose_name': '压测接口信息',
                'db_table': 'locustapi',
            },
        ),
    ]
